Шишка Антон (Варіант 30)

In [1]:
import numpy as np

1. Створіть одновимірний масив (вектор) з добутками квадратів кожного числа та його подвійного значення, починаючи з 1, та виведіть його значення.

In [2]:
numbers = np.arange(1, 11)

result = (numbers**2) * (2*numbers)

print(result)

[   2   16   54  128  250  432  686 1024 1458 2000]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями добутків косинусів кожного числа та його попереднього, починаючи з 1, та виведіть його значення.

In [3]:
matrix = np.zeros((3, 3))

for i in range(3):
    for j in range(3):
        matrix[i, j] = np.cos((i + 1) * (j + 1))

print(matrix)

[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.41614684 -0.65364362  0.96017029]
 [-0.9899925   0.96017029 -0.91113026]]


3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами від -10 до 10 та знайдіть відсоток чисел, які мають останню цифру 5.

In [16]:
random_array = np.random.randint(-10, 11, size=(5, 5))

numbers_with_last_digit_5 = random_array[random_array % 10 == 5]
percentage = (len(numbers_with_last_digit_5) / random_array.size) * 100

print(f"Масив:\n{random_array}\n")
print(f"Відсоток чисел з останньою цифрою 5: {percentage}%")

Масив:
[[ -5  -7  -4   6  -3]
 [ -4   5 -10   4  -2]
 [  6   2   9   8  -1]
 [-10  -2  -9   6   5]
 [ -9  -9   2   3 -10]]

Відсоток чисел з останньою цифрою 5: 12.0%


4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами від -1.6 до 1.6 та виведіть його значення.

In [5]:
random_array = np.random.uniform(-1.6, 1.6, size=(4, 4))

print(random_array)

[[ 1.57393545 -1.53137349 -0.08833845 -1.22137385]
 [-1.09621832  1.50443946 -0.40750347  0.92477985]
 [ 0.44838048 -1.46757925 -1.45022453 -1.06669723]
 [-1.43666357  1.09564723  1.56664305 -0.23228789]]


5. Створіть два одновимірних масиви розміром 8, заповніть їх випадковими цілими числами в діапазоні від 3 до 8 та виконайте на них поелементні операції додавання, віднімання та множення.

In [6]:
array1 = np.random.randint(3, 9, size=8)
array2 = np.random.randint(3, 9, size=8)

addition_result = array1 + array2
subtraction_result = array1 - array2
multiplication_result = array1 * array2

print("Масив 1:", array1)
print("Масив 2:", array2)
print("Результат додавання:", addition_result)
print("Результат віднімання:", subtraction_result)
print("Результат множення:", multiplication_result)

Масив 1: [6 3 3 4 8 7 7 3]
Масив 2: [5 6 8 6 7 4 6 5]
Результат додавання: [11  9 11 10 15 11 13  8]
Результат віднімання: [ 1 -3 -5 -2  1  3  1 -2]
Результат множення: [30 18 24 24 56 28 42 15]


6. Створіть два вектори розміром 4, заповніть їх довільними дійсними числами та знайдіть їх скалярний добуток.

In [7]:
vector1 = np.random.rand(4)
vector2 = np.random.rand(4)

scalar_product = np.dot(vector1, vector2)

print("Вектор 1:", vector1)
print("Вектор 2:", vector2)
print("Скалярний добуток:", scalar_product)

Вектор 1: [0.62983175 0.02202242 0.11135624 0.68535023]
Вектор 2: [0.11915666 0.67117611 0.45643467 0.48982662]
Скалярний добуток: 0.47635920112325403


7. Створіть дві матриці розміром 3x2 та 2x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 20 та перемножте їх між собою.

In [14]:
matrix1 = np.random.randint(1, 21, size=(3, 2))
matrix2 = np.random.randint(1, 21, size=(2, 4))

result = np.dot(matrix1, matrix2)

print("Матриця 1:")
print(matrix1)
print("\nМатриця 2:")
print(matrix2)
print("\nРезультат перемноження:")
print(result)

Матриця 1:
[[11  2]
 [ 3 15]
 [ 4  3]]

Матриця 2:
[[ 3  5 16  1]
 [ 9  8 10 17]]

Результат перемноження:
[[ 51  71 196  45]
 [144 135 198 258]
 [ 39  44  94  55]]


8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 7 та знайдіть її обернену матрицю.

In [12]:
matrix = np.random.randint(1, 8, size=(3, 3))

print("Початкова матриця:")
print(matrix)

determinant = np.linalg.det(matrix)
if determinant == 0:
    print("Не можливо знайти обернену матрицю.")
else:
    inverse_matrix = np.linalg.inv(matrix)

    print("Обернена матриця:")
    print(inverse_matrix)

Початкова матриця:
[[3 4 3]
 [1 7 2]
 [6 4 1]]
Обернена матриця:
[[ 0.01369863 -0.10958904  0.17808219]
 [-0.15068493  0.20547945  0.04109589]
 [ 0.52054795 -0.16438356 -0.23287671]]


9. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 0 до 5 та транспонуйте її.

In [17]:
matrix = np.random.randint(0, 6, size=(5, 5))

print("Початкова матриця:")
print(matrix)

transposed_matrix = np.transpose(matrix)

print("\nТранспонована матриця:")
print(transposed_matrix)

Початкова матриця:
[[1 3 2 1 0]
 [3 5 3 3 0]
 [4 5 5 5 0]
 [3 3 3 4 5]
 [3 0 3 2 1]]

Транспонована матриця:
[[1 3 4 3 3]
 [3 5 5 3 0]
 [2 3 5 3 3]
 [1 3 5 4 2]
 [0 0 0 5 1]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами від 0 до 1, і знайдіть добуток матриці на вектор.

In [18]:
matrix = np.random.rand(3, 4)

vector = np.random.rand(4)

result = np.dot(matrix, vector)

print("Матриця:")
print(matrix)

print("\nВектор:")
print(vector)

print("\nДобуток матриці на вектор:")
print(result)

Матриця:
[[0.5800369  0.32661058 0.66565604 0.65913751]
 [0.43115223 0.02528455 0.42497725 0.48144749]
 [0.80482007 0.55293793 0.09674742 0.07123584]]

Вектор:
[0.69210272 0.96653158 0.90873881 0.6228746 ]

Добуток матриці на вектор:
[1.73259204 1.00891469 1.22373926]


11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть суму добутків елементів кожного стовпця матриці на відповідний елемент вектору.

In [19]:
matrix = np.random.rand(2, 3)

vector = np.random.randint(1, 11, size=3)

result = np.sum(matrix * vector, axis=0)

print("Матриця:")
print(matrix)

print("\nВектор:")
print(vector)

print("\nСума добутків елементів кожного стовпця матриці:")
print(result)

Матриця:
[[0.75311517 0.17551528 0.94562393]
 [0.88672969 0.40252842 0.66089731]]

Вектор:
[3 6 5]

Сума добутків елементів кожного стовпця матриці:
[4.91953459 3.46826217 8.03260617]


12. Створіть дві матриці розміром 7x7, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть відношення всіх елементів другої матриці до відповідних елементів першої матриці (поелементне ділення).

In [20]:
matrix1 = np.random.randint(1, 11, size=(7, 7))
matrix2 = np.random.randint(1, 11, size=(7, 7))

result = matrix2 / matrix1

print("Матриця 1:")
print(matrix1)

print("\nМатриця 2:")
print(matrix2)

print("\nВідношення елементів другої матриці до елементів першої матриці:")
print(result)

Матриця 1:
[[ 1  4  8  5  2  2  4]
 [ 6 10  8  5  4  9  6]
 [10  2  6  9  7 10  5]
 [ 1  1  5  4  9 10  5]
 [ 2  6  4  2 10  1  8]
 [ 1 10  1  2 10  5  5]
 [ 8  4 10  3  8  4  5]]

Матриця 2:
[[ 6  2  6  3  2  9 10]
 [ 9  9 10  6  6  4  5]
 [ 6  8  1  7  2  2  7]
 [ 5  4  1  2  7  1  1]
 [10  9 10  1  7  7  1]
 [ 5  5  3  1  3 10  4]
 [ 9  9  8  9  5  8  8]]

Відношення елементів другої матриці до елементів першої матриці:
[[6.         0.5        0.75       0.6        1.         4.5
  2.5       ]
 [1.5        0.9        1.25       1.2        1.5        0.44444444
  0.83333333]
 [0.6        4.         0.16666667 0.77777778 0.28571429 0.2
  1.4       ]
 [5.         4.         0.2        0.5        0.77777778 0.1
  0.2       ]
 [5.         1.5        2.5        0.5        0.7        7.
  0.125     ]
 [5.         0.5        3.         0.5        0.3        2.
  0.8       ]
 [1.125      2.25       0.8        3.         0.625      2.
  1.6       ]]


13. Створіть дві матриці розміром 5x5, заповніть їх випадковими цілими числами в діапазоні від -10 до 10 та знайдіть суму їх елементів.

In [21]:
matrix1 = np.random.randint(-10, 11, size=(5, 5))
matrix2 = np.random.randint(-10, 11, size=(5, 5))

sum_matrix1 = np.sum(matrix1)
sum_matrix2 = np.sum(matrix2)

print("Матриця 1:")
print(matrix1)

print("\nМатриця 2:")
print(matrix2)

print("\nСума елементів матриці 1:", sum_matrix1)
print("Сума елементів матриці 2:", sum_matrix2)

Матриця 1:
[[10 -1  1  5  7]
 [-2  6  6 -8 -9]
 [-2 -2 -8  0 -6]
 [ 7  0 -1  8 -6]
 [ 2 -5 -9 -3  2]]

Матриця 2:
[[ 7 -9 -3 -2 -1]
 [-2 -2 -8 -2 -3]
 [ 2 10  4  4 -1]
 [-2 -8 -5  1  0]
 [ 8 -8  1  2  8]]

Сума елементів матриці 1: -8
Сума елементів матриці 2: -9


14. Створіть матрицю розміром 10x10, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть кількість елементів, що дорівнюють нулю.

In [27]:
matrix = np.random.randint(1, 101, size=(10, 10))

zero_count = np.count_nonzero(matrix == 0)

print("Матриця:")
print(matrix)

print("\nКількість елементів, що дорівнюють нулю:", zero_count)

Матриця:
[[ 15  98  56   1  75 100  54  89  62  24]
 [ 25  47  68 100  84  67  62  77  22  86]
 [ 57  36  90  67  61  89   5  20  86  34]
 [ 55  50  85  59  90   4  31  50  45  14]
 [ 13  83  21  61  98  96  51  62  63  41]
 [ 24  72   9  35  79  28  77  28  12  96]
 [ 34  13  52  95  75  68  84  32  26   5]
 [ 71   4  11  78  77  23  68  47  26  63]
 [ 96  78  16  94  39  71  13  57  35  47]
 [ 96   5  24  71  54  25  15   2  80   6]]

Кількість елементів, що дорівнюють нулю: 0


15. Створіть матрицю розміром 7x7, заповніть її випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть вектор-стовпчик, що містить суму кубів елементів кожного стовпця матриці.

In [28]:
matrix = np.random.uniform(-1, 1, size=(7, 7))

sum_cubed_columns = np.sum(matrix**3, axis=0)

sum_cubed_columns = sum_cubed_columns.reshape(-1, 1)

print("Матриця:")
print(matrix)

print("\nСума кубів елементів кожного стовпця:")
print(sum_cubed_columns)

Матриця:
[[-0.86257472 -0.68380951 -0.01289883 -0.48069446  0.12112278 -0.52192886
   0.37299245]
 [ 0.99484793  0.54583444 -0.45423033 -0.80259724  0.27671816  0.27472509
   0.98123816]
 [ 0.20396253 -0.57245331 -0.30792039 -0.86571953 -0.73242821  0.76004759
  -0.34277336]
 [-0.47355096 -0.80588458 -0.76095864 -0.31139598  0.41756253  0.09781989
   0.92306456]
 [ 0.46278937 -0.37873835 -0.33047009 -0.85361183  0.87782563 -0.12055584
   0.98880742]
 [ 0.39042917 -0.75653686  0.17290509  0.36123599 -0.61453171 -0.11602001
  -0.74250906]
 [-0.15122095  0.43643845 -0.98303147 -0.16256003  0.54167294 -0.59285216
   0.08114888]]

Сума кубів елементів кожного стовпця:
[[ 0.40030273]
 [-1.27229663]
 [-1.54443091]
 [-1.88624649]
 [ 0.30614734]
 [ 0.10686479]
 [ 2.30084886]]


Висновок:

В цій роботі я навчився використовувати деякі елементи з бібліотеки numpy, а саме:
  1. Знаходження добутків квадратів чисел та їх подвійних значень

  2. Заповнення матриці косинусами та її виведення

  3. Визначення відсотку чисел з останньою цифрою

  4. Створення масиву та виконання операцій

  5. Знаходження скалярного добутку векторів

  6. Множення двох матриць

  7. Знаходження оберненої матриці

  8. Транспонування матриці

  9. Виконання поелементного ділення матриць

  10. Знаходження суми кожного стовпця матриці в кубі
